# Build the project and deploy it to GitHub pages
name: Deploy

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master, main]

jobs:
  deploy:
    name: Build and Deploy Site

    runs-on: ubuntu-latest

    steps:
    - name: Checkout website repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      shell: bash
      run: ./ci/install.sh
    - name: Build with Lektor
      shell: bash
      run: ./ci/build.sh
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        BRANCH: gh-pages    # The branch the action should deploy to
        FOLDER: ./website-lektor-icon-build    # The folder the action should deploy
        CLEAN: true    # Automatically remove deleted files from the deploy branch
