# Run the project's linting suite via Pre-Commit
name: Lint

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master, main, '*.*', 'staging*']
  pull_request:
    branches: [master, main, '*.*', 'staging*']

jobs:
  lint:
    name: Lint with Pre-Commit

    runs-on: ubuntu-latest

    steps:
    - name: Checkout website repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install baseline dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install development dependencies
      run: python -m pip install --upgrade -r requirements-dev.txt
    - name: Run main Pre-Commit hooks
      uses: pre-commit/action@v2.0.3
